name: Change Shell
on:
  push:
    paths: "change-shell.yml"
jobs:
 print:
  runs-on: ubuntu-latest
  steps:
    - shell: bash
      run: echo "${SHELL}"
    - shell: python
      run: |
        import os
        print(os.environ['PATH'])