name: Compare functions
on:
  push:
    paths: "compare-functions-yml"
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello','ell') }}   #[ell]を含むか
          STARTS_FUNC: ${{ startsWith('Hello','He') }}    #[He]で始まるか
          ENDS_FUNC: ${{ endsWith('Hello','lo') }}        #[lo]で終わるか