name: Conditions
on:
  push:
    paths: "conditons.yml"
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '777') }}   #ワークフロー実行IDで分岐