name: JSON Functions
on:
  push:
    paths: "json-functions.yml"
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }}    #githubコンテキストをJSON文字列でダンプ