name: Variables
on:
  push:
    paths: "variables.yml"
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}    #USERNAMEの参照
    steps:
      - run: echo "${USERNAME}"